<?php
       session_start();
       if(isset($_SESSION['session_id']))
              {
                  unset($_SESSION['session_id']);
                  header("Location:admin_login.php");
              }
       else 
              {
                  header("Location:admin_login.php");
              }
?>
